### ISSUE TITLE
Ldap error when running the operator with IS 6.x.x

### ISSUE THREAD

**Issue by RukshanJS** [wso2/k8s-wso2is-operator#20]
**Description:**
Since the newer 6.x versions of the wso2is removed the ldap userstore connection by default, if you try to run the operator versions of the operator with newer IS 6.x versions, errors similar to the following will occur.

```
[2023-05-19 14:08:10,228] [] ERROR {org.wso2.carbon.user.core.ldap.LDAPConnectionContext} - Error obtaining connection. Cannot parse url: ldap://localhost:-1 javax.naming.NamingException: Cannot parse url: ldap://localhost:-1 [Root exception is java.net.MalformedURLException: unsupported authority: localhost:-1]
	at java.naming/com.sun.jndi.ldap.LdapURL.<init>(LdapURL.java:115)
	at java.naming/com.sun.jndi.ldap.DefaultLdapDnsProvider.lookupEndpoints(DefaultLdapDnsProvider.java:47)
```

This issue is already fixed with https://github.com/wso2/k8s-wso2is-operator/pull/19 but added here for tracking purposes

**Comment by RukshanJS** [comment]
Fixed with #19
